version: "3.9"

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data-1:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 2s
      timeout: 3s
      retries: 3
      start_period: 3s

  server:
    container_name: function
    build: .
    ports:
      - "6767:6767"
    depends_on:
      - mongo
    restart: always

volumes:
  mongo-data-1: